public class HabitacionSencilla extends Hotel {
    private String nombreDelTitular;
    private int numeroDeAcompaniantes;
    private int numeroDeHabitacion;
    public String get...
    public int get...
    public int get...
    public void set...
    public void set...
    public void set...
}
